"""The shipped translation pack: translations that need no network at all.

Everything GuruFlow says in a curated lesson - narration, objectives, checkpoint
feedback, repair explanations, flashcards, report copy - is a *fixed* string. It
does not depend on the learner, so it can be translated once, checked in, and
served instantly forever after.

That is what this module reads. ``data/translations/<language>.json`` holds
``{english source: translation}`` for each of the twelve extended languages,
generated by ``tools/build_translation_pack.py`` and committed to the repo.

Why it matters: without the pack, a learner who picks Tamil waits on a live API
call for every string and gets English whenever that call is rate-limited. With
it, Tamil is instant, deterministic, offline, and identical on a judge's laptop
to what we tested. The engines in ``engines.py`` then only handle what the pack
cannot know in advance - lessons about arbitrary uploaded material.

The pack is also a **write-back cache**: a string translated live at runtime is
appended to the on-disk pack (unless ``GURUFLOW_TRANSLATION_WRITEBACK=0``), so
the same string is never paid for twice, even across restarts.
"""

from __future__ import annotations

import json
import logging
import os
import threading
from pathlib import Path

logger = logging.getLogger(__name__)

PACK_DIR = Path(
    os.environ.get(
        "GURUFLOW_TRANSLATION_PACK_DIR",
        Path(__file__).resolve().parents[2] / "data" / "translations",
    )
)

# language -> {english source: translation}. Loaded lazily, once per process.
_packs: dict[str, dict[str, str]] = {}
_loaded: set[str] = set()
# Disk writes happen on request threads; keep them from interleaving.
_write_lock = threading.Lock()


def _writeback_enabled() -> bool:
    return os.environ.get("GURUFLOW_TRANSLATION_WRITEBACK", "1").strip().lower() not in (
        "0",
        "false",
        "no",
        "off",
    )


def pack_path(language: str) -> Path:
    return PACK_DIR / f"{language}.json"


def load(language: str) -> dict[str, str]:
    """Return the shipped pack for a language, loading it once per process."""
    if language in _loaded:
        return _packs.get(language, {})

    _loaded.add(language)
    path = pack_path(language)
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        _packs[language] = {}
        return _packs[language]
    except (OSError, json.JSONDecodeError) as exc:
        # A corrupt pack must not take the lesson down with it.
        logger.warning("Translation pack for %s is unreadable: %s", language, exc)
        _packs[language] = {}
        return _packs[language]

    entries = raw.get("entries", raw) if isinstance(raw, dict) else {}
    _packs[language] = {
        str(k): str(v) for k, v in entries.items() if isinstance(v, str) and v.strip()
    }
    logger.debug("Loaded %s pack entries for %s", len(_packs[language]), language)
    return _packs[language]


def lookup(text: str, language: str) -> str | None:
    """Translation for ``text``, or None if the pack does not carry it."""
    return load(language).get(text)


def coverage(language: str) -> int:
    """How many strings the shipped pack covers - surfaced in /health."""
    return len(load(language))


def remember(text: str, translation: str, language: str) -> None:
    """Add a live translation to the pack, in memory and on disk.

    Best-effort by design: a read-only checkout or a full disk costs us the
    write, not the lesson.
    """
    pack = load(language)
    if pack.get(text) == translation:
        return
    pack[text] = translation

    if not _writeback_enabled():
        return

    with _write_lock:
        path = pack_path(language)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            payload = {
                "language": language,
                "note": (
                    "Generated by tools/build_translation_pack.py and extended at "
                    "runtime. Equations, numbers and unit symbols are preserved "
                    "verbatim; see services/translation/pack.py."
                ),
                "entries": dict(sorted(pack.items())),
            }
            # Write beside the target then replace, so a crash mid-write cannot
            # leave a half-written pack behind.
            tmp = path.with_suffix(".json.tmp")
            tmp.write_text(
                json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            os.replace(tmp, path)
        except OSError as exc:
            logger.debug("Could not persist %s pack: %s", language, exc)


def reset_cache() -> None:
    """Forget loaded packs (tests only)."""
    _packs.clear()
    _loaded.clear()


__all__ = [
    "PACK_DIR",
    "coverage",
    "load",
    "lookup",
    "pack_path",
    "remember",
    "reset_cache",
]
